version: "3.7"
services:
  nca-toolkit:
    container_name: nca-toolkit
    image: ghcr.io/no-code-architects/no-code-architects-toolkit:latest
    ports:
      - ${APP_PORT}:8080
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - PORT=8080
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    networks:
      - tipi_main_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/toolkit/test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  tipi_main_network:
    external: true