version: "3.7"
services:
  nca-toolkit:
    container_name: nca-toolkit
    image: ghcr.io/no-code-architects/no-code-architects-toolkit:latest
    ports:
      - ${APP_PORT}:8080
    environment:
      - API_KEY=${API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_REGION=${S3_REGION}
      - GCP_SA_CREDENTIALS=${GCP_SA_CREDENTIALS}
      - GCP_BUCKET_NAME=${GCP_BUCKET_NAME}
      - LOCAL_STORAGE_PATH=${LOCAL_STORAGE_PATH:-/app/data}
      - MAX_QUEUE_LENGTH=${MAX_QUEUE_LENGTH:-0}
      - GUNICORN_WORKERS=${GUNICORN_WORKERS}
      - GUNICORN_TIMEOUT=${GUNICORN_TIMEOUT:-300}
      - PORT=8080
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    networks:
      - tipi_main_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/toolkit/test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  tipi_main_network:
    external: true