version: '3.9'
services:
  wordpress4:
    container_name: wordpress4
    image: wordpress:6.8.1
    environment:
      - WORDPRESS_DB_HOST=wordpress4-db
      - WORDPRESS_DB_NAME=wordpress4
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress:/var/www/html
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - wordpress4-db
    networks:
      - tipi_main_network
    labels:
      traefik.enable: true
      traefik.http.middlewares.wordpress4-redirect.redirectscheme.scheme: https
      traefik.http.services.wordpress4.loadbalancer.server.port: 80
      traefik.http.routers.wordpress4-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.wordpress4-insecure.entrypoints: web
      traefik.http.routers.wordpress4-insecure.service: wordpress4
      traefik.http.routers.wordpress4-insecure.middlewares: wordpress4-redirect
      traefik.http.routers.wordpress4.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.wordpress4.entrypoints: websecure
      traefik.http.routers.wordpress4.service: wordpress4
      traefik.http.routers.wordpress4.tls.certresolver: myresolver
      traefik.http.routers.wordpress4-local-insecure.rule: Host(`wordpress4.${LOCAL_DOMAIN}`)
      traefik.http.routers.wordpress4-local-insecure.entrypoints: web
      traefik.http.routers.wordpress4-local-insecure.service: wordpress4
      traefik.http.routers.wordpress4-local-insecure.middlewares: wordpress4-redirect

      traefik.http.routers.wordpress4-local.entrypoints: websecure
      traefik.http.routers.wordpress4-local.service: wordpress4
      traefik.http.routers.wordpress4-local.tls: true
      runtipi.managed: true
  wordpress4-db:
    container_name: wordpress4-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress4
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true